services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php
    build:
      context: docker/nginx
      args:
        SERVER_VERSION: $SERVER_VERSION
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./sources:$PHP_USER_HOME_DIRECTORY
    ports:
      - $SERVER_PORT:80

  php:
    container_name: php
    restart: unless-stopped
    depends_on:
      - mariadb
    build:
      context: docker/php
      args:
        PHP_VERSION: $PHP_VERSION
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    user: php
    volumes:
      - ./sources:$PHP_USER_HOME_DIRECTORY
      - ./db:$PHP_USER_HOME_DIRECTORY/db

  migration:
    container_name: migration
    restart: unless-stopped
    depends_on:
      - mariadb
    build:
      context: docker/php
      args:
        PHP_VERSION: $PHP_VERSION
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    user: php
    volumes:
      - ./db:$PHP_USER_HOME_DIRECTORY
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    build:
      context: docker/mariadb
      args:
        DATABASE_VERSION: $DATABASE_VERSION
    tty: true
    stdin_open: true
    user: root
    env_file: .env
    working_dir: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MARIADB_USER: $DATABASE_USER
      MARIADB_PASSWORD: $DATABASE_PASSWORD
      MARIADB_DATABASE: $DATABASE_NAME
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
  node:
    container_name: node
    build:
      context: ./docker/node
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./sources:/app
    command: sass --watch ./src/scss/main.scss ./dist/css/main.css --poll
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
    ports:
      - "8080:80"
    depends_on:
      - mariadb
